### PR TITLE
Upgraded to Raven 7.1.0

### PR DESCRIPTION
**Pull request by donbeave**
with some cleanup

### CODE REVIEW

**Comment by benorama** [comment]
Thanks!

**Comment by donbeave** [comment]
@benorama thanks for merge. Btw, when you prepare to deploy it to Bintray?

**Comment by benorama** [comment]
I'll give it a test probably tomorrow on our apps and publish it after that.

**Comment by benorama** [comment]
I've just published it!

**Comment by donbeave** [comment]
Thank you!

**Pull request merged**
