### PR TITLE
Introducing new configurations on sentry 

### PR DESCRIPTION
**Pull request by anujku**
I ran author rewrite script (https://help.github.com/articles/changing-author-info/) so thats why it is showing so many changes. I had two users on my computer and it was not showing my actual account on github. Only changes are in ```README.md``` and ```GrailsLog4jSentryAppender.groovy```. Let me know if that is ok.

https://github.com/agorapulse/grails-raven/compare/master...anujku:develop?expand=1

- Introducing optional subsystems as a filter on sentry dashboard similar to what you see on`YouTrack`.Let me know if something like this will make sense ? 
Default subsystem will be `MISC`, exceptions with package name starting with `org.` will be under `LIBRARY`.

- Introducing optional priority filter based on predefined priority map containing level and list of exceptions with that level of priority. Similarly library exceptions are MID level priority. 

- Introducing optional classname parameter that will add the class name for the exception on sentry.

- Removing comma separated values for logger, tags, levels and using List or Map which is a much better way to do the same in groovy.

I think it will really improve experience while browsing errors on sentry.The current logic though can always be be improved.(?)

### CODE REVIEW

**Comment by anujku** [comment]
More things will be added.

**Comment by anujku** [comment]
I ran author-rewrite script (https://help.github.com/articles/changing-author-info/)
as I was using two accounts and it was not showing my actual account. Sorry for this.

**Comment by benorama** [comment]
I've released 6.0.0.4 version.
I'll give it a try today.

Thanks!

2015-03-18 23:20 GMT+01:00 Coveralls <notifications@github.com>:

**Comment by anujku** [comment]
Thank you very much !!

**Pull request merged**
